# Generated by Django 5.1.4 on 2026-10-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approval_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
