# Generated by Django 5.1.4 on 2026-08-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_productpricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('in_use', 'In use'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('sold', 'Sold')], max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=80, null=True)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_units', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_changes', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stock.equipmentunit')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('quantity_in_use', models.IntegerField(default=0)),
                ('quantity_damaged', models.IntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, max_length=80, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product')),
            ],
        ),
    ]
