# Generated by Django 5.1.4 on 2026-09-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('count_correction', 'Count correction'), ('to_damaged', 'Moved to damaged'), ('from_damaged', 'Returned from damaged'), ('to_in_use', 'Moved to in use'), ('from_in_use', 'Returned from in use')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('before_in_stock', models.IntegerField()),
                ('after_in_stock', models.IntegerField()),
                ('before_in_use', models.IntegerField()),
                ('after_in_use', models.IntegerField()),
                ('before_damaged', models.IntegerField()),
                ('after_damaged', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='stock.inventory')),
            ],
            options={
                'ordering': ['-created_at', '-adjustment_id'],
            },
        ),
    ]
