# Generated by Django 5.1.4 on 2026-10-06 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_tax_category'),
        ('stock', '0002_inventoryadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase_receipt', 'Purchase received'), ('purchase_cancel', 'Purchase cancelled'), ('sale', 'Sale'), ('sale_return', 'Sale return'), ('sale_void', 'Sale void'), ('adjust_count', 'Count correction'), ('to_damaged', 'Moved to damaged'), ('from_damaged', 'Returned from damaged'), ('to_in_use', 'Moved to in use'), ('from_in_use', 'Returned from in use'), ('internal_consumption', 'Used internally'), ('to_shop_asset', 'Made shop asset'), ('opening', 'Opening stock'), ('merge_in', 'Merged in'), ('merge_out', 'Merged out'), ('bundle_breakdown', 'Bundle breakdown')], max_length=30)),
                ('bucket', models.CharField(choices=[('in_stock', 'In stock'), ('in_use', 'In use'), ('damaged', 'Damaged')], max_length=10)),
                ('quantity_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-movement_id'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stockmove_product_created'), models.Index(fields=['created_at'], name='stockmove_created')],
            },
        ),
    ]
