# Generated by Django 5.1.4 on 2026-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_backfill_stock_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('in_use', 'In use'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('sold', 'Sold'), ('shop_asset', 'Shop asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase received'), ('purchase_cancel', 'Purchase cancelled'), ('sale', 'Sale'), ('sale_return', 'Sale return'), ('sale_void', 'Sale void'), ('adjust_count', 'Count correction'), ('to_damaged', 'Moved to damaged'), ('from_damaged', 'Returned from damaged'), ('to_in_use', 'Moved to in use'), ('from_in_use', 'Returned from in use'), ('internal_consumption', 'Used internally'), ('to_shop_asset', 'Made shop asset'), ('from_shop_asset', 'Returned from shop asset'), ('opening', 'Opening stock'), ('merge_in', 'Merged in'), ('merge_out', 'Merged out'), ('bundle_breakdown', 'Bundle breakdown')], max_length=30),
        ),
    ]
