# Generated by Django 5.1.4 on 2026-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productpricing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productpricing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('product',), name='one_current_price_per_product'),
        ),
    ]
