# Generated by Django 5.1.4 on 2026-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productpricing_one_current_price_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(choices=[('A', 'Exempt (0%)'), ('B', 'Standard (18%)')], default='B', max_length=1),
        ),
    ]
