# Generated by Django 5.1.4 on 2026-10-06 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMerge',
            fields=[
                ('merge_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merged_into', to='catalog.product')),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_received', to='catalog.product')),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_merges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-merge_id'],
            },
        ),
    ]
