# Generated by Django 5.1.4 on 2026-08-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
