# Generated by Django 5.1.4 on 2026-08-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
