# Generated by Django 5.1.4 on 2026-10-06 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productmerge'),
        ('purchasing', '0004_alter_purchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'template_id'],
            },
        ),
        migrations.CreateModel(
            name='BundleTemplateComponent',
            fields=[
                ('template_component_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_per_bundle', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['template_component_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItemComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_per_bundle', models.PositiveIntegerField()),
                ('allocated_paid_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_invoiced_cost', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['component_id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='bundle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='line_kind',
            field=models.CharField(choices=[('single', 'Single'), ('pack', 'Pack'), ('bundle', 'Bundle')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('line_kind', 'bundle'), _connector='OR'), name='purchase_item_product_required_unless_bundle'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_kind', 'bundle'), _negated=True), ('product__isnull', True), _connector='OR'), name='purchase_item_bundle_has_no_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_pack__gte', 1)), name='purchase_item_units_per_pack_positive'),
        ),
        migrations.AddField(
            model_name='bundletemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundletemplate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_templates', to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='bundletemplatecomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_template_components', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundletemplatecomponent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='purchasing.bundletemplate'),
        ),
        migrations.AddField(
            model_name='purchaseitemcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_item_components', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='purchaseitemcomponent',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='purchasing.purchaseitem'),
        ),
        migrations.AddConstraint(
            model_name='bundletemplatecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('qty_per_bundle__gte', 1)), name='bundle_template_component_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='bundletemplatecomponent',
            constraint=models.UniqueConstraint(fields=('template', 'product'), name='bundle_template_product_once'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitemcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('qty_per_bundle__gte', 1)), name='purchase_component_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitemcomponent',
            constraint=models.UniqueConstraint(fields=('purchase_item', 'product'), name='purchase_component_product_once_per_bundle'),
        ),
    ]
