# Generated by Django 5.1.4 on 2026-10-06 15:25

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_tax_category(apps, schema_editor):
    # Snapshot each line's VAT category from its product. Re-runnable: only
    # rows still null are touched.
    Product = apps.get_model("catalog", "Product")
    PurchaseItem = apps.get_model("purchasing", "PurchaseItem")
    PurchaseItemComponent = apps.get_model("purchasing", "PurchaseItemComponent")
    category = Subquery(Product.objects.filter(pk=OuterRef("product_id")).values("tax_category")[:1])
    PurchaseItem.objects.filter(tax_category__isnull=True, product__isnull=False).update(tax_category=category)
    PurchaseItemComponent.objects.filter(tax_category__isnull=True).update(tax_category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_min_price'),
        ('purchasing', '0006_packs_and_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='has_vat_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tax_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitemcomponent',
            name='tax_category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.RunPython(backfill_tax_category, migrations.RunPython.noop),
    ]
