# Generated by Django 5.1.4 on 2026-10-06 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_product_min_price'),
        ('stock', '0005_shop_asset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('retired', 'Retired'), ('returned_to_stock', 'Returned to stock')], default='in_service', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(choices=[('from_stock', 'Taken from stock'), ('pre_owned', 'Already owned')], max_length=20)),
                ('acquired_at', models.DateField(default=django.utils.timezone.localdate)),
                ('acquisition_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_spare', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_assets_created', to=settings.AUTH_USER_MODEL)),
                ('equipment_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_assets', to='stock.equipmentunit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_assets', to='catalog.product')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='operations.shopasset')),
            ],
            options={
                'ordering': ['name', 'asset_id'],
            },
        ),
        migrations.CreateModel(
            name='InternalConsumption',
            fields=[
                ('consumption_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purpose', models.CharField(choices=[('replacement', 'Replacement'), ('repair', 'Repair'), ('shop_setup', 'Shop setup'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_approved', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='catalog.product')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_recorded', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_taken', to=settings.AUTH_USER_MODEL)),
                ('shop_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='operations.shopasset')),
            ],
            options={
                'ordering': ['-created_at', '-consumption_id'],
            },
        ),
        migrations.CreateModel(
            name='ShopAssetEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('in_service', 'In service'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('retired', 'Retired'), ('returned_to_stock', 'Returned to stock')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('in_service', 'In service'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('retired', 'Retired'), ('returned_to_stock', 'Returned to stock')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_asset_events_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.shopasset')),
                ('consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events', to='operations.internalconsumption')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_events', to='operations.shopasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_asset_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-event_id'],
            },
        ),
        migrations.AddIndex(
            model_name='internalconsumption',
            index=models.Index(fields=['created_at'], name='consumption_created'),
        ),
    ]
