# Generated by Django 5.1.4 on 2026-10-06 00:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_shopprofile'),
        ('purchasing', '0005_purchase_payments'),
        ('sales', '0005_sale_payments_customer_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'In (from customer)'), ('out', 'Out (to supplier)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('receipt_group', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.purchase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.payment')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'ordering': ['-paid_at', '-payment_id'],
                'indexes': [models.Index(fields=['paid_at'], name='payment_paid_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('purchase__isnull', True), ('sale__isnull', False)), models.Q(('purchase__isnull', False), ('sale__isnull', True)), _connector='OR'), name='payment_exactly_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('reversal_of__isnull', True)), models.Q(('amount__lt', 0), ('reversal_of__isnull', False)), _connector='OR'), name='payment_positive_unless_reversal')],
            },
        ),
    ]
