# Generated by Django 5.1.4 on 2026-10-06 01:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_backfill_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='max_staff_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
