# Generated by Django 5.1.4 on 2026-10-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_shopprofile_max_staff_discount_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('close_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_by_method', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-close_id'],
                'constraints': [models.UniqueConstraint(fields=('cashier', 'business_date'), name='one_close_per_cashier_per_day')],
            },
        ),
    ]
