# Generated by Django 5.1.4 on 2026-10-06 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_module_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='alert_asset_replacements',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_asset_window_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_below_cost_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_below_cost_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_billing_diff_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_cash_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_discount_spike_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text="A cashier's discount % this week above this multiple of their 8-week average.", max_digits=5),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_overdue_days',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='alert_top_sellers',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
