# Generated by Django 5.1.4 on 2026-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_category',
            field=models.CharField(choices=[('A', 'Exempt (0%)'), ('B', 'Standard (18%)')], default='B', max_length=1),
            preserve_default=False,
        ),
    ]
