# Generated by Django 5.1.4 on 2026-10-06 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_discount_amount(apps, schema_editor):
    # Existing lines already store list_price and unit_price; derive the discount
    # (negative for a markup). cost_at_sale stays null: the cost at that moment
    # was never recorded, and reports fall back to the weighted average.
    SaleItem = apps.get_model("sales", "SaleItem")
    SaleItem.objects.update(
        discount_amount=(models.F("list_price") - models.F("unit_price")) * models.F("quantity")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_payments_customer_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sale_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_discount_amount, migrations.RunPython.noop),
    ]
